<?php

declare(strict_types=1);

namespace App\Infrastructure\Database;

/**
 * Every table of the framework's own metadata schema (architecture §10, all
 * phases) plus Laravel's housekeeping tables. Physical record tables are never
 * given these names, and they can never be bound to a form. A test keeps this
 * list equal to the ERD.
 */
final class FrameworkTables
{
    /** @var list<string> */
    public const ERD = [
        'access_policies',
        'access_tokens',
        'action_steps',
        'actions',
        'announcement_dismissals',
        'announcements',
        'api_tokens',
        'applications',
        'approval_decisions',
        'approval_requests',
        'archived_records',
        'assignment_rules',
        'assignments',
        'audit_chain_heads',
        'audit_logs',
        'automation_runs',
        'automation_steps',
        'automation_triggers',
        'automations',
        'blueprint_instances',
        'blueprint_versions',
        'blueprints',
        'bulk_operations',
        'business_calendars',
        'collections',
        'conditions',
        'config_packages',
        'currencies',
        'dashboard_widgets',
        'dashboards',
        'delegations',
        'department_closure',
        'departments',
        'document_templates',
        'download_jobs',
        'download_profile_columns',
        'download_profile_filters',
        'download_profiles',
        'download_schedules',
        'duplicate_rules',
        'egress_allowlist',
        'email_queue',
        'email_templates',
        'encryption_keys',
        'environment_drift_reports',
        'error_groups',
        'error_logs',
        'exchange_rates',
        'export_jobs',
        'extension_versions',
        'extensions',
        'external_data_sources',
        'external_forms',
        'external_users',
        'feature_flags',
        'field_access_rules',
        'field_groups',
        'field_options',
        'field_templates',
        'fields',
        'files',
        'filters',
        'form_versions',
        'forms',
        'help_content',
        'holidays',
        'home_screens',
        'impersonation_sessions',
        'import_jobs',
        'import_mappings',
        'in_app_notifications',
        'inbound_endpoints',
        'justification_attachments',
        'justification_reason_codes',
        'justification_rules',
        'justifications',
        'legal_holds',
        'locales',
        'login_attempts',
        'menu_items',
        'merge_history',
        'migration_plans',
        'migration_steps',
        'notification_channels',
        'notification_deliveries',
        'notification_rules',
        'number_sequences',
        'operations_alert_rules',
        'organizations',
        'outbox_events',
        'page_widgets',
        'pages',
        'password_histories',
        'permission_assignments',
        'permissions',
        'personal_data_requests',
        'print_layouts',
        'publish_locks',
        'queue_claims',
        'queue_forms',
        'queues',
        'record_access_rules',
        'record_comments',
        'recycle_bin',
        'reference_previews',
        'relations',
        'reports',
        'retention_policies',
        'retention_runs',
        'roles',
        'saved_view_shares',
        'saved_views',
        'scheduled_tasks',
        'schema_reconciliation_reports',
        'schema_snapshots',
        'search_configs',
        'sessions',
        'settings',
        'signature_requests',
        'sla_rules',
        'sla_timers',
        'status_history',
        'status_mappings',
        'statuses',
        'storage_quotas',
        'subject_keys',
        'submission_journal',
        'submission_throttles',
        'sync_jobs',
        'sync_runs',
        'theme_assets',
        'themes',
        'tour_progress',
        'tours',
        'transitions',
        'translations',
        'trusted_devices',
        'units_of_measure',
        'usage_metrics',
        'user_preferences',
        'user_roles',
        'users',
        'view_columns',
        'view_panels',
        'views',
        'webhook_deliveries',
        'webhooks',
    ];

    /** @var list<string> */
    public const LARAVEL = ['migrations', 'cache', 'cache_locks', 'jobs', 'job_batches', 'failed_jobs', 'password_reset_tokens'];

    public static function contains(string $table): bool
    {
        $t = strtolower($table);

        return in_array($t, self::ERD, true) || in_array($t, self::LARAVEL, true);
    }
}
