<?php

declare(strict_types=1);

namespace App\Infrastructure\Database\Drivers;

use App\Infrastructure\Database\Contracts\DatabaseDriver;
use App\Infrastructure\Database\Naming;
use App\Infrastructure\Database\Specs\BackupResult;
use App\Infrastructure\Database\Specs\ColumnSpec;
use App\Infrastructure\Database\Specs\DdlImpact;
use App\Infrastructure\Database\Specs\DdlOperation;
use App\Infrastructure\Database\Specs\ForeignKeySpec;
use App\Infrastructure\Database\Specs\IndexSpec;
use App\Infrastructure\Database\Specs\LogicalType;
use App\Infrastructure\Database\Specs\TableSpec;
use Illuminate\Database\Connection;
use Illuminate\Database\Query\Builder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\ColumnDefinition;
use Illuminate\Support\Facades\Storage;
use InvalidArgumentException;

/**
 * DDL is generated by building a Blueprint against the connection's schema
 * grammar (our engine-specific grammars), so both drivers share the same
 * driver-neutral logic and differ only where the engines differ.
 */
abstract class AbstractDriver implements DatabaseDriver
{
    /** Allowed JSON path syntax: `$.a.b[0]` — validated before use in raw SQL. */
    private const JSON_PATH = '/^\$(\.[A-Za-z_][A-Za-z0-9_]*|\[\d+\])*$/';

    /** Allowed identifiers for raw SQL fragments. */
    private const IDENTIFIER = '/^[A-Za-z_][A-Za-z0-9_]{0,127}$/';

    public function __construct(protected readonly Connection $connection) {}

    public function createTable(TableSpec $table): array
    {
        return $this->blueprint($table->name, function (Blueprint $t) use ($table): void {
            $t->create();
            foreach ($table->columns as $column) {
                $this->applyColumn($t, $column);
            }
            foreach ($table->indexes as $index) {
                $this->applyIndex($t, $index);
            }
            foreach ($table->foreignKeys as $fk) {
                $this->applyForeignKey($t, $fk);
            }
        });
    }

    public function addColumn(string $table, ColumnSpec $column): array
    {
        return $this->blueprint($table, fn (Blueprint $t) => $this->applyColumn($t, $column));
    }

    public function renameTable(string $from, string $to): array
    {
        $this->assertIdentifier($to);

        return $this->blueprint($from, fn (Blueprint $t) => $t->rename($to));
    }

    public function renameColumn(string $table, string $from, string $to): array
    {
        $this->assertIdentifier($from);
        $this->assertIdentifier($to);

        return $this->blueprint($table, fn (Blueprint $t) => $t->renameColumn($from, $to));
    }

    public function alterColumnType(string $table, ColumnSpec $column): array
    {
        return $this->blueprint($table, function (Blueprint $t) use ($column): void {
            $this->applyColumn($t, $column, addChecks: false)->change();
        });
    }

    public function addIndex(string $table, IndexSpec $index): array
    {
        return $this->blueprint($table, fn (Blueprint $t) => $this->applyIndex($t, $index));
    }

    public function addForeignKey(string $table, ForeignKeySpec $foreignKey): array
    {
        return $this->blueprint($table, fn (Blueprint $t) => $this->applyForeignKey($t, $foreignKey));
    }

    public function dropForeignKey(string $table, string $name): array
    {
        $this->assertIdentifier($name);

        return $this->blueprint($table, fn (Blueprint $t) => $t->dropForeign($name));
    }

    public function estimateDdlImpact(string $table, DdlOperation $operation): DdlImpact
    {
        $support = $this->supportsOnlineDdl($operation);
        $rows = $this->tableStats($table)->rows;
        $costMicrosPerRow = match (true) {
            $support->lockLevel === 'metadata' => 0,
            in_array($operation, [DdlOperation::AddIndex, DdlOperation::AddForeignKey], true) => 2,
            default => 6,
        };

        return new DdlImpact(
            rows: $rows,
            estimatedMs: max(50, intdiv($rows * $costMicrosPerRow, 1000)),
            online: $support->online,
            lockLevel: $support->lockLevel,
        );
    }

    public function tables(): array
    {
        return array_values(array_map(
            static fn (array $t): string => (string) $t['name'],
            $this->connection->getSchemaBuilder()->getTables(),
        ));
    }

    public function columns(string $table): array
    {
        return array_values(array_map(static fn (array $c): array => [
            'name' => (string) $c['name'],
            'type' => (string) $c['type'],
            'nullable' => (bool) $c['nullable'],
            'default' => $c['default'],
        ], $this->connection->getSchemaBuilder()->getColumns($table)));
    }

    public function indexes(string $table): array
    {
        return array_values(array_map(static fn (array $i): array => [
            'name' => (string) $i['name'],
            'columns' => array_values($i['columns']),
            'unique' => (bool) $i['unique'],
            'primary' => (bool) $i['primary'],
        ], $this->connection->getSchemaBuilder()->getIndexes($table)));
    }

    public function foreignKeys(string $table): array
    {
        return array_values(array_map(static fn (array $f): array => [
            'name' => $f['name'] ?? null,
            'columns' => array_values($f['columns']),
            'foreign_table' => (string) $f['foreign_table'],
            'foreign_columns' => array_values($f['foreign_columns']),
            'on_delete' => isset($f['on_delete']) ? strtolower((string) $f['on_delete']) : null,
        ], $this->connection->getSchemaBuilder()->getForeignKeys($table)));
    }

    public function jsonContains(Builder $query, string $column, string $path, string|int|float|bool $value): Builder
    {
        $this->assertIdentifier($column);

        return $query->whereJsonContains($column.$this->arrowPath($path), $value);
    }

    public function caseInsensitiveLike(Builder $query, string $column, string $term, string $mode = 'contains'): Builder
    {
        // A column may be qualified by its table (`table.column`).
        foreach (explode('.', $column, 2) as $part) {
            $this->assertIdentifier($part);
        }
        // '!' is the escape character: it needs no quoting in either engine's
        // string literals (a backslash does in MySQL), and '[' is a wildcard
        // on SQL Server.
        $escaped = str_replace(['!', '%', '_', '['], ['!!', '!%', '!_', '!['], $term);

        // Both databases are created with case- and accent-insensitive collations.
        $pattern = match ($mode) {
            'equals' => $escaped,
            'starts' => $escaped.'%',
            default => '%'.$escaped.'%',
        };

        return $query->whereRaw($this->wrap($column)." like ? escape '!'", [$pattern]);
    }

    public function lockForUpdate(Builder $query): Builder
    {
        return $query->lockForUpdate();
    }

    public function logicalBackup(array $tables, string $disk, string $directory): BackupResult
    {
        $storage = Storage::disk($disk);
        $rowsPerTable = [];
        $hash = hash_init('sha256');
        $bytes = 0;

        foreach ($tables as $table) {
            $this->assertIdentifier($table);
            $schema = json_encode([
                'table' => $table,
                'columns' => $this->columns($table),
                'indexes' => $this->indexes($table),
                'foreign_keys' => $this->foreignKeys($table),
            ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE);
            $storage->put("{$directory}/{$table}.schema.json", $schema);
            hash_update($hash, $schema);
            $bytes += strlen($schema);

            $lines = '';
            $count = 0;
            $hasId = in_array('id', array_column($this->columns($table), 'name'), true);
            $query = $this->connection->table($table);
            $writer = function ($rows) use (&$lines, &$count): void {
                foreach ($rows as $row) {
                    $lines .= json_encode((array) $row, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE)."\n";
                    $count++;
                }
            };
            if ($hasId) {
                $query->orderBy('id')->chunkById(1000, $writer);
            } else {
                $writer($query->get());
            }
            $storage->put("{$directory}/{$table}.jsonl", $lines);
            hash_update($hash, $lines);
            $bytes += strlen($lines);
            $rowsPerTable[$table] = $count;
        }

        return new BackupResult($disk, $directory, $rowsPerTable, $bytes, hash_final($hash));
    }

    public function maxIdentifierLength(): int
    {
        return Naming::MAX_IDENTIFIER;
    }

    /**
     * @param  callable(Blueprint): mixed  $callback
     * @return list<string>
     */
    protected function blueprint(string $table, callable $callback): array
    {
        $this->assertIdentifier($table);
        $blueprint = new Blueprint($this->connection, $table);
        $callback($blueprint);

        return array_values($blueprint->toSql());
    }

    protected function applyColumn(Blueprint $t, ColumnSpec $c, bool $addChecks = true): ColumnDefinition
    {
        $this->assertIdentifier($c->name);
        $id = $c->type === LogicalType::Id || $c->unsigned || $c->name === 'id' || str_ends_with($c->name, '_id');
        $definition = match ($c->type) {
            LogicalType::Id => $t->id($c->name),
            LogicalType::BigInt => $id ? $t->unsignedBigInteger($c->name) : $t->bigInteger($c->name),
            LogicalType::Int => $t->integer($c->name),
            LogicalType::SmallInt => $t->smallInteger($c->name),
            LogicalType::Bool => $t->boolean($c->name),
            LogicalType::Decimal => $t->decimal($c->name, $c->precision ?? 19, $c->scale ?? 4),
            LogicalType::Str => $t->string($c->name, $c->length ?? 255),
            LogicalType::Code => $t->addColumn('code', $c->name, ['length' => $c->length ?? 64]),
            LogicalType::Hash => $t->addColumn('hash', $c->name),
            LogicalType::Text => $t->text($c->name),
            LogicalType::LongText => $t->longText($c->name),
            LogicalType::Json => $t->json($c->name),
            LogicalType::Uuid => $t->uuid($c->name),
            LogicalType::DateTime => $t->dateTime($c->name, 6),
            LogicalType::Date => $t->date($c->name),
            LogicalType::Time => $t->time($c->name, 0),
            LogicalType::Enum => $t->addColumn('code', $c->name, ['length' => max(32, ...array_map('strlen', $c->values ?: ['']))]),
        };
        if ($c->type !== LogicalType::Id) {
            $definition->nullable($c->nullable);
        }
        if ($c->default !== null) {
            $definition->default($c->default);
        }
        if ($addChecks && $c->type === LogicalType::Enum) {
            $values = implode(', ', array_map(static fn (string $v): string => "'".str_replace("'", "''", $v)."'", $c->values));
            $t->check(Naming::constraint('ck', $t->getTable(), [$c->name]), $this->wrap($c->name)." in ({$values})");
        }
        if ($addChecks && $c->type === LogicalType::Json && ($check = $this->jsonColumnCheck($c->name)) !== null) {
            $t->check(Naming::constraint('ck', $t->getTable(), [$c->name, 'json']), $check);
        }

        return $definition;
    }

    protected function applyIndex(Blueprint $t, IndexSpec $i): void
    {
        $this->assertIdentifier($i->name);
        if ($i->unique && $i->nullableColumns !== []) {
            $t->filteredUnique($i->name, $i->columns, $i->nullableColumns);
        } elseif ($i->unique) {
            $t->unique($i->columns, $i->name);
        } else {
            $t->index($i->columns, $i->name);
        }
    }

    protected function applyForeignKey(Blueprint $t, ForeignKeySpec $f): void
    {
        $this->assertIdentifier($f->name);
        $rule = strtolower($f->onDelete);
        if (! in_array($rule, ['no action', 'cascade', 'set null', 'restrict'], true)) {
            throw new InvalidArgumentException("Invalid ON DELETE rule [{$f->onDelete}].");
        }
        $t->foreign($f->column, $f->name)->references($f->referencesColumn)->on($f->referencesTable)->onDelete($rule);
    }

    protected function wrap(string $identifier): string
    {
        return $this->connection->getQueryGrammar()->wrap($identifier);
    }

    protected function assertIdentifier(string $identifier): void
    {
        if (preg_match(self::IDENTIFIER, $identifier) !== 1) {
            throw new InvalidArgumentException("Invalid identifier [{$identifier}].");
        }
    }

    protected function assertJsonPath(string $path): void
    {
        if (preg_match(self::JSON_PATH, $path) !== 1) {
            throw new InvalidArgumentException("Invalid JSON path [{$path}].");
        }
    }

    /** `$.a.b` → `->a->b` for the query builder's JSON helpers. */
    private function arrowPath(string $path): string
    {
        $this->assertJsonPath($path);
        $segments = array_filter(explode('.', substr($path, 1)), static fn (string $s): bool => $s !== '');

        return implode('', array_map(static fn (string $s): string => '->'.$s, $segments));
    }
}
